Upgrade
linuxserver/docker-mariadb pull request #112
Opened 2022-12-09 21:18 UTC by nemchik

- Use the `mariadb` specific commands (ex: `mysqladmin` is a symlink to `mariadb-admin`)
- Document information about upgrading the database using `mariadb-upgrade`
- Add logic during init to check if an upgrade is required and notify the user in logs

2022-12-19 19:11 UTC, thespad requested changes
![image](https://user-images.githubusercontent.com/8425502/208501735-709bafdd-6cbe-4de9-ba3c-938a3f18805a.png)

2023-01-22 03:42 UTC, nemchik commented
> ![image](https://user-images.githubusercontent.com/8425502/208501735-709bafdd-6cbe-4de9-ba3c-938a3f18805a.png)

Reworked to have the upgrade check run after `svc-mariadb` is ready. It is also now completely silent unless an upgrade is needed (and the `MYSQL_ROOT_PASSWORD` variable contains a valid root password).

2023-01-22 15:57 UTC, thespad commented on root/etc/s6-overlay/s6-rc.d/init-mariadb-upgrade/run
> +#################################################################
I would suggest rewording this to include something like "Stop any service that are accessing databases in this container. and then run the command..."

2023-01-22 17:15 UTC, nemchik commented on root/etc/s6-overlay/s6-rc.d/init-mariadb-upgrade/run
> +#################################################################
Resolved in https://github.com/linuxserver/docker-mariadb/pull/112/commits/ad6f6c57af7a7539d3831891fe026b3d2f20b916

2023-01-22 17:32 UTC, thespad approved these changes

2023-01-22 18:18 UTC, merged